jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      sudo apt-get install libtommath0
    displayName: 'Install dependencies'

  - script:
      wget -O Firebird-3.0.3.32900-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0.amd64.tar.gz"
    displayName: 'Download Firebird'

  - script: |
      tar xzvf Firebird-3.0.3.32900-0.amd64.tar.gz
      (cd Firebird-3.0.3.32900-0.amd64; sudo ./install.sh -silent)
      sudo usermod -a -G firebird $USER
    displayName: 'Install Firebird'

  - script: |
      sg firebird -c "yarn"
      sg firebird -c "yarn bootstrap"
      sg firebird -c "yarn test"
    displayName: 'Build and test'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - powershell: Invoke-WebRequest -Uri "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0_x64.zip" -OutFile "C:\Temp\Firebird-3.0.3.32900-0_x64.zip"
    displayName: 'Download Firebird'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'C:\Temp\Firebird-3.0.3.32900-0_x64.zip'
      destinationFolder: C:\Firebird
    displayName: 'Extract Firebird'

  - script: |
      set PATH=C:\Firebird;%PATH%
      yarn
      yarn bootstrap
      yarn test
    displayName: 'Build and test'
